// src/app/admin/layout.tsx (ou votre layout admin)
import type { Metadata } from "next"; 
import { Bebas_Neue, Open_Sans } from "next/font/google";
import "../../app/globals.css";
import NavBarVAdmin from "../components/navBar-V-Admin";
import dynamic from 'next/dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col min-h-screen" style={{ background: "black" }}>
           

      <header>
        <NavBarVAdmin 
          items={[
            { title: "Users", link: "/admin/users" },
            { title: "News-Letter", link: "/admin/newsLetter" },
            {
              title: "Evénements",
              subItems: [
                { title: "Formations", link: "/admin/formations" },
                { title: "Evenements", link: "/admin/evenements" },
                { title: "Communaute", link: "/admin/Communaute" },
              ],
            },
            { title: "Blog", link: "admin/blog" },
            { title: "Contact", link: "admin/contact" },
          ]}
        />
      </header>

      <div className="flex-grow">{children}</div>
    </div>
  );
}
