// src/app/layout.tsx
import type { Metadata } from "next";
import { Bebas_Neue, Open_Sans } from "next/font/google";
import "./globals.css";

const BebasNeue = Bebas_Neue({
  weight: "400",
  variable: "--font-bebas-neue",
  subsets: ["latin"],
});

const openSansRegular = Open_Sans({
  weight: "400",
  variable: "--font-open-sans-regular",
  subsets: ["latin"],
});

const openSansBold = Open_Sans({
  weight: "700",
  variable: "--font-open-sans-bold",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${BebasNeue.variable}
          ${openSansRegular.variable}
          ${openSansBold.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
