// src/app/layout.tsx
import type { Metadata } from "next";
import { Bebas_Neue, Open_Sans } from "next/font/google";
import NavBarH from "./components/navBar-H";
import Footer from "./components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen"
        style={{ background: "black" }}>
        <header>
          <NavBarH
            logo="/LogoNeth.png"
            items={[
              { title: "Accueil", link: "/" },
              { title: "Communauté", link: "/communaute",
                subItems: [
                  { title: "Bienvenue", link: "/communaute" },
                  { title: "Evénements", link: "/evenements" },
                ],
               },
              {
                title: "Services",
                subItems: [
                  { title: "Formations", link: "/formations" },
                  { title: "Création d'entreprise", link: "/creation-entreprise" },
                  { title: "Facture", link: "/facture" },
                ],
              },
              { title: "Blog", link: "/blog" },
              { title: "Contact", link: "/contact" },
            ]}
          />
        </header>

       {/*-----------0 DEBUT espace entre les sections */} 
       <div className="h-10 md:h-15"></div>

        <main className="flex-grow">{children}</main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
